refactor: rewrite systemctl-install script for chroot-systemctl installation logic

diff --git a/bin/systemctl-install b/bin/systemctl-install
--- a/bin/systemctl-install
+++ b/bin/systemctl-install
@@ -1,58 +1,181 @@
 #!/bin/sh
 
-# This script generates mount commands for various container runtimes.
+# This script is used to install chroot-systemctl related files to the container.
 
-printf_mount() {
-    local mount_arg="$1"
-    local mount_eq="$2"
-    local source="$3"
-    local mount_seg="$4"
-    local target="$5"
-    local mount_opts="$6"
-    if [ -z "$target" ]; then
-        target="$source"
-    fi
-    if [ -z "$mount_opts" ]; then
-        mount_opts=""
-    else
-        mount_opts="${mount_seg}${mount_opts}"
-    fi
-    printf "%s%s%s%s%s%s " "$mount_arg" "$mount_eq" "$source" "$mount_seg" "$target" "$mount_opts"
+CHECK_PATH="bin lib sbin etc"
+SYSTEMCTL_ROOT="${0%/*}/.."
+
+usage() {
+    cat <<EOF
+Usage: ${0##*/} [chrootdir] [command]
+    help        Display this help and exit
+    install     Install chroot-systemctl related files to the container (default)
+    uninstall   Uninstall chroot-systemctl related files from the container
+If 'chrootdir' is not specified, the files will be installed to the current system.
+EOF
 }
 
-printf_docker_mount() { printf_mount "-v" " " "$1" ":" "$2" "$3"; }
-printf_singularity_mount() { printf_mount "-B" " " "$1" ":" "$2" "$3"; }
-printf_proot_mount() { printf_mount "-b" " " "$1" ":" "$2"; }
-printf_pdlogin_mount() { printf_mount "--bind" " " "$1" ":" "$2"; }
+#### Auxiliary functions ####
+check_text() {
+    file2check="$1"
+    # Check if file command is available
+    if ! command -v file >/dev/null 2>&1; then
+        # Skipping text check
+        return 0
+    fi
+    # Verify if $file2check is a script
+    if ! file -b --mime-type "$file2check" | grep -q '^text/'; then
+        return 1
+    fi
+    return 0
+}
 
-# Check & Mount Applets in Chroot
-bin_dir=${0%/*}
-if [ -z "$chrootdir" ]; then
-    chrootdir="$PWD/rootfs"
+check_install_applet() {
+    # Usage: check_install_applet <applet_path>
+    # => install <applet_path> to $chrootdir/<applet_path>
+    # e.g. check_install_applet sbin/init => install sbin/init to $chrootdir/sbin/init
+    local applet_path="$1"
+    local target_path="$chrootdir/$applet_path"
+    # Check if target_path exists and is a text file
+    if [ -f "$target_path" ] || [ -L "$target_path" ]; then
+        check_text "$target_path" && return 0
+        install_applet "$applet_path"
+    fi
+    # Install applet
+    return 0
+}
+
+check_uninstall_applet() {
+    local applet_path="$1"
+    local target_path
+    if [ -z "$2" ]; then
+        target_path="$chrootdir/$applet_path"
+    else
+        target_path="$chrootdir/$2"
+    fi
+    # Check if target_path exists and is a text file
+    if [ -f "$target_path" ] || [ -L "$target_path" ]; then
+        check_text "$target_path" &&
+        rm -f "$target_path"
+    fi
+    return 0
+}
+
+install_applet() {
+    local applet_path="$1"
+    local source_path="$SYSTEMCTL_ROOT/$applet_path"
+    local target_path
+    if [ -z "$2" ]; then
+        target_path="$chrootdir/$applet_path"
+    else
+        target_path="$chrootdir/$2"
+    fi
+
+    if [ -x "$source_path" ]; then
+        install -Dm755 "$source_path" "$target_path"
+    else
+        install -Dm644 "$source_path" "$target_path"
+    fi
+}
+
+### Main functions ###
+# This function handles the main installation logic in three stages:
+# 1. Conditionally replace files in CHECK_PATH.
+# 2. Forcibly install core applets.
+# 3. Forcibly install all files from the 'local' directory.
+install_systemctl() {
+    for path in $CHECK_PATH; do
+        if [ ! -d "$SYSTEMCTL_ROOT/$path" ]; then
+            continue
+        fi
+        # Install everything in the specified path
+        find "$SYSTEMCTL_ROOT/$path" \( -type f -o -type l \) | \
+            sed "s|^$SYSTEMCTL_ROOT/||" | \
+            while IFS= read -r relative_path; do
+                if [ -n "$relative_path" ]; then
+                    check_install_applet "$relative_path"
+                fi
+            done
+    done
+    # Enforce the installation of systemctl applet
+    install_applet "bin/systemctl3.py"
+    [ ! -e "$chrootdir/sbin/init" ] && install_applet "sbin/init"
+    find "$SYSTEMCTL_ROOT/local" \( -type f -o -type l \) | \
+        sed "s|^$SYSTEMCTL_ROOT/||" | \
+        while IFS= read -r relative_path; do
+            if [ -n "$relative_path" ]; then
+                install_applet "$relative_path" "/usr/$relative_path"
+            fi
+        done
+  
+}
+
+uninstall_systemctl() {
+    if [ "$chrootdir" = "/" ]; then
+        cat <<EOF
+############################## WARNING ##############################
+    Uninstalling from the current system is not supported,
+    Please specify a chroot directory to uninstall from.
+    See \`${0##*/} help\` for usage.
+    If you have to remove from the current system,
+    please override via package manager;
+    or manually remove those files;
+    or run \`${0##*/} uninstall\` outside the chroot environment.
+#####################################################################
+EOF
+        return 1
+    else
+        for path in $CHECK_PATH; do
+            find "$SYSTEMCTL_ROOT/$path" \( -type f -o -type l \) | \
+                sed "s|^$SYSTEMCTL_ROOT/||" | \
+                while IFS= read -r relative_path; do
+                    if [ -n "$relative_path" ]; then
+                        check_uninstall_applet "$relative_path"
+                    fi
+                done
+        done
+        find "$SYSTEMCTL_ROOT/local" \( -type f -o -type l \) | \
+            sed "s|^$SYSTEMCTL_ROOT/||" | \
+            while IFS= read -r relative_path; do
+                if [ -n "$relative_path" ]; then
+                    check_uninstall_applet "$relative_path" "/usr/$relative_path"
+                fi
+            done
+        return 0
+    fi
+}
+
+### Main script starts here ###
+if [ "$1" = "help" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+    usage
+    exit 0
 fi
 
-check_chroot_applet() {
-    # Usage: check_chroot_applet <target-container> <applet>...
-    # Required external variables: $bin_dir $chrootdir $applet_path
-    # e.g. bin_dir=foo chrootdir=bar applet_path=/bin check_chroot_applet docker "baz"
-    # bar/bin/baz exist => output: -v foo/baz:/bin/baz
-    local target_container="$1"; shift
-    local chroot_path="$chrootdir/$applet_path"
-    for applet in "$@"; do
-        if [ -x "$chroot_path/$applet" ] || [ -L "$chroot_path/$applet" ]; then
-            eval printf_${target_container}_mount "$bin_dir/$applet" "$applet_path/$applet" "ro"
-        fi
-    done
-}
+if [ -z "$1" ]; then
+    chrootdir="/"
+else
+    if [ ! -d "$1" ]; then
+        echo "Invalid chroot directory: $1" 1>&2
+        exit 1
+    fi
+    chrootdir="$1"
+    shift
+fi
 
-printf_systemctl_mounts() {
-    # Usage: printf_systemctl_mounts <target-container>
-    local target_container="$1"
-    applet_path=/bin check_chroot_applet "$target_container" journalctl systemctl
-    applet_path=/lib/systemd/systemd check_chroot_applet "$target_container" systemd
-    applet_path=/sbin check_chroot_applet "$target_container" halt poweroff reboot runlevel shutdown telinit
-    eval printf_${target_container}_mount "$bin_dir/init" "/sbin/init" ro
-    eval printf_${target_container}_mount "$bin_dir/systemctl3.py" "/bin/systemctl3.py" ro
-}
-
-printf_systemctl_mounts "$@"
+case "$1" in
+    help)
+        usage
+        ;;
+    install|"")
+        # Default action is to install
+        install_systemctl
+        ;;
+    uninstall)
+        uninstall_systemctl
+        ;;
+    *)
+        echo "Unknown command: $1" 1>&2
+        usage
+        exit 1
+        ;;
+esac
